Traceback (most recent call last):
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/joelchan/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def get_details(d, key): # fill out / check the parameters
    value = d.get(d)
    
    # write the body of the function
    return value# write the return value

classes_to_instructors = {"INST126": "Chan", "INST201": "Sauter"}
get_details(classes_to_instructors, "INST126")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/xz/_hjc5hsx743dclmg8n5678nc0000gn/T/ipykernel_89773/2397902500.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0mclasses_to_instructors[0m [0;34m=[0m [0;34m{[0m[0;34m"INST126"[0m[0;34m:[0m [0;34m"Chan"[0m[0;34m,[0m [0;34m"INST201"[0m[0;34m:[0m [0;34m"Sauter"[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mget_details[0m[0;34m([0m[0mclasses_to_instructors[0m[0;34m,[0m [0;34m"INST126"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/var/folders/xz/_hjc5hsx743dclmg8n5678nc0000gn/T/ipykernel_89773/2397902500.py[0m in [0;36mget_details[0;34m(d, key)[0m
[1;32m      1[0m [0;32mdef[0m [0mget_details[0m[0;34m([0m[0md[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m [0;31m# fill out / check the parameters[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0mvalue[0m [0;34m=[0m [0md[0m[0;34m.[0m[0mget[0m[0;34m([0m[0md[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m     [0;31m# write the body of the function[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0;32mreturn[0m [0mvalue[0m[0;31m# write the return value[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: unhashable type: 'dict'
TypeError: unhashable type: 'dict'

